name: 'Setup Triggers Box Comment'
description: 'Finds or creates a comment on a PR and populates it with workflow trigger checkboxes.'

inputs:
  pr-number:
    description: 'The number of the pull request'
    required: true
  commit-hash:
    description: 'The commit SHA to associate with the comment'
    required: true
  head-ref:
    description: 'The head ref (branch) of the pull request'
    required: true
  required-workflows:
    description: 'A JSON string array of required workflow names'
    required: true
  optional-workflows:
    description: 'A JSON string array of optional workflow names'
    required: false
  github-token:
    description: 'The GitHub token for API calls'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run setup comment script
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        COMMIT_HASH: ${{ inputs.commit-hash }}
        HEAD_REF: ${{ inputs.head-ref }}
        REQUIRED_WORKFLOWS: ${{ inputs.required-workflows }}
        OPTIONAL_WORKFLOWS: ${{ inputs.optional-workflows }}
        ACTION_BOT: 'devops-eh'
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          // ${{ github.action_path }} is a special variable that gives the absolute
          // path to the directory where this action.yml file is located.
          const script = require(process.env.GITHUB_ACTION_PATH + '/script.js');
          await script({github, context, core});