name: Build E2E Assets -- HR Web App

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "Hello, world! Build E2E Assets -- HR Web App"
