name: Build E2E Assets -- HR Web App

on:
  workflow_dispatch: # Only allow manual triggering via API/checkbox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world! Build E2E Assets -- HR Web App"
