name: Handle triggers box events

on:
  issue_comment:
    types: [edited]

jobs:
  handle-events:
    name: Handle triggers box events
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != null && github.event.comment.user.login == 'hani-nguyen-eh'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Handle triggers box events
        uses: ./.github/actions/handle-triggers-box-events
        with:
          event-payload: ${{ toJSON(github.event) }}
          required-workflows: "build-dev"
          optional-workflows: "build-preview,build-e2e-assets--hr-web-app"
          environment-mappings: '{"build-dev": "Development", "build-preview": "Preview"}'
          github-token: ${{ secrets.GITHUB_TOKEN }}
