name: Handle triggers box events

on:
  issue_comment:
    types: [edited]

jobs:
  call-handle-events-workflow:
    name: Call handle events workflow
    uses: ./.github/workflows/shared-handle-triggers-box-events.yml
    if: github.event.issue.pull_request != null && github.event.comment.user.login == 'hani-nguyen-eh'
    with:
      event-payload: ${{ toJSON(github.event) }}
      environment-mappings: '{"build-dev": "Development", "build-preview": "Preview", "build-e2e-assets--hr-web-app": null}'
    secrets:
      GH_TOKEN: ${{ secrets.GH_DISPATCH_TOKEN }}
