name: Handle triggers box events

on:
  issue_comment:
    types: [edited]

jobs:
  call-handle-events-workflow:
    name: Call handle events workflow
    runs-on: ubuntu-latest
    steps:
      - name: Call handle events workflow
        uses: thinkei/shared-actions/.github/actions/handle-triggers-box-events@chore/make-share-workflow
        if: github.event.issue.pull_request != null && github.event.comment.user.login == 'hani-nguyen-eh'
        with:
          event-payload: ${{ toJSON(github.event) }}
          workflow-dispatch-config-json: '{"build-dev": "Development", "build-preview": "Preview", "build-e2e-assets--hr-web-app": null}'
          github-token: ${{ secrets.GH_DISPATCH_TOKEN }}
